name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build Web Assets
        run: npm run build

      - name: Install Capacitor CLI and Android platform
        run: |
          npm install @capacitor/cli @capacitor/android
          npx cap sync android

      - name: Build Android APK
        working-directory: android
        run: ./gradlew assembleDebug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Kernel-Sanctum-APK
          path: android/app/build/outputs/apk/debug/app-debug.apk